# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html


llm:
  api_type: "openai"
  api_version: "2024-02-15-preview"
  base_url: "http://175.45.13.117:53999/v1"
  api_key: '32de14a039364bafb28799119ab5781c'
  model: "internlm2"
